[tool.poetry]
name = "logdetective"
version = "0.1.0"
description = ""
authors = ["Jiri Podivin <jpodivin@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
include = ["logdetective/drain3.ini"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
llama-cpp-python = "^0.2.56"
tiktoken = "^0.6.0"
drain3 = "^0.9.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
logdetective = 'logdetective.logdetective:main'

